
spring:
  main:
    allow-circular-references: true
    lazy-initialization: false
  application:
    name: ServicesApplication
    baseUrl: http://localhost:8080
  datasource:
    tomcat:
      max-active: 10
      max-idle: 5
      min-idle: 2
      initial-size: 5
      remove-abandoned: true
    url: jdbc:postgresql://localhost:5432/AttendanceApplication
    username: postgres
    password: postgres
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  jpa:
    show-sql=true:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: gate68dev@gmail.com
    password: tdjieojezrmecsyl
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
upload:
  path: D:/
  maxFileSize: 500
